# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        cache: ~
        slider:
            quality: 75
            filters:
                fixed: { width: 800, height: 400 }
        default:
            quality: 75
            filters:
                fixed: { width: 300, height: 300 }
        referent:
            quality: 75
            filters:
                fixed: { width: 130, height: 130 }
        thanks:
            quality: 75
            filters:
                fixed: { width: 130, height: 130 }