vich_uploader:
    db_driver: orm
    mappings:
        avatars:
            uri_prefix:         '/images/thanks'
            upload_destination: '%kernel.project_dir%/public/images/thanks'
            delete_on_remove: true
            delete_on_update: true
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            directory_namer:
                service: vich_uploader.namer_directory_current_date_time
                options: {date_time_property: uploadTimestamp, date_time_format: 'Y/d/m/H'}
